{{ cookiecutter.repo_name }}/notebooks/notebook_preamble.ipy
{{ cookiecutter.repo_name }}/requirements.txt

Added notebook_preamble.ipy and updated requirements.txt accordingly

---

{{ cookiecutter.repo_name }}/notebooks/notebook_preamble.ipy

Removed `project_dir` from path in `notebook_preamble.ipy`

---

hooks/post_gen_project.sh

#28 `data/raw` and `data/interim` are in `.gitignore` so need force adding

Post-gen hook adds data dirs

---

{{ cookiecutter.repo_name }}/Makefile

Removed bad newline

---

docs/docs/index.md
{{ cookiecutter.repo_name }}/Makefile
{{ cookiecutter.repo_name }}/conda_environment.yaml

grep filter conda_environment.yaml fixes gcc pkg

---

cookiecutter.json
docs/docs/quickstart.md

61 s3 naming

---

{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/__init__.py
{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/config/logging.yaml

Fix malformed template variable

---

.github/workflows/test.yml
cookiecutter.json
docs/docs/quickstart.md
tests/Dockerfile
tests/conftest.py
tests/docker-compose.yml
tests/test_creation.py
{{ cookiecutter.repo_name }}/Makefile
{{ cookiecutter.repo_name }}/bin/conda_activate.sh
{{ cookiecutter.repo_name }}/bin/create_bucket.sh
{{ cookiecutter.repo_name }}/bin/create_repo.sh
{{ cookiecutter.repo_name }}/bin/install_metaflow_aws.sh
{{ cookiecutter.repo_name }}/setup.py
{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/__init__.py
{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/config/logging.yaml

Addition of github actions means `dev` branch can be done away with.

Release changes from dev onto master

---

{{ cookiecutter.repo_name }}/requirements_dev.txt

REMOVE: pandoc, pandoc-crossref, mypy

---

docs/docs/css/extra.css
docs/docs/examples/index.md
docs/docs/examples/industrial_taxonomy.md
docs/docs/faq.md
docs/docs/index.md
docs/docs/quickstart.md
docs/docs/roadmap.md
docs/docs/structure.md
docs/mkdocs.yml
requirements.txt
{{ cookiecutter.repo_name }}/README.md

63 69 70 Documentation improvements

---

{{ cookiecutter.repo_name }}/bin/create_repo.sh

Fix Github repo creation script

---

docs/docs/quickstart.md

Improve quickstart docs

---

.github/labels.yml
.github/release-drafter.yml
.github/workflows/labeler.yml
.github/workflows/release.yml

95 Formalise release procedure

---

.github/workflows/test.yml

93 Add MacOS to CI

---

.github/pull_request_template.md
.github/release-drafter.yml
.github/workflows/release.yml

Refine release actions

---

docs/docs/structure.md

Correct docs mistake

---

.github/workflows/test.yml

Run tests on all PRs

---

docs/docs/quickstart.md

127 docs choose version

---

docs/mkdocs.yml

Fix mkdocs tabbing

---

{{ cookiecutter.repo_name }}/.recipes/MetaflowAWS.md

Fix metaflowconfig path.

---

README.md
docs/docs/css/extra.css

Remove outdated asciicast

---

DEVELOPERS.md
README.md
docs/README.md

Developer docs

---

{{ cookiecutter.repo_name }}/Makefile
{{ cookiecutter.repo_name }}/requirements.txt

Removed packages in requirements as they are not needed by all projects and can cause version issues. All users should add their own project requirements. Closes #152

152 remove requirements

---

docs/docs/structure.md

---
- Updated the docs for the cookiecutter structure, except for the Make file part. 
Checklist:

[168] Updating cookiecutter structure doc

---

.pre-commit-config.yaml
DEVELOPERS.md
docs/README.md
docs/docs/css/extra.css
docs/docs/guidelines.md
docs/docs/quickstart.md
docs/docs/structure.md
docs/mkdocs.yml
{{ cookiecutter.repo_name }}/.recipes/GithubCreation.md
{{ cookiecutter.repo_name }}/.recipes/MetaflowAWS.md
{{ cookiecutter.repo_name }}/docs/conf.py
{{ cookiecutter.repo_name }}/setup.py
{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/__init__.py

Adds nbstripout pre-commit hook, addressing #183 
---
Checklist:

chore(hooks): add pre-commit hook to strip notebook outputs

---

docs/docs/quickstart.md
hooks/post_gen_project.sh
tests/test_creation.py
{{ cookiecutter.repo_name }}/.pre-commit-config.yaml

Removed 0_setup_cookiecutter as it is redundant

---

.pre-commit-config.yaml
{{ cookiecutter.repo_name }}/.cookiecutter/config
{{ cookiecutter.repo_name }}/.pre-commit-config.yaml
{{ cookiecutter.repo_name }}/Makefile

Addresses #219 , #220 
---
Checklist:

v0.3.1 Patches

---

.github/workflows/docs.yml

Fix docs deployment
